version: '3.8'

services:
  app:
    container_name: fenz-osm-manager
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
      # CHANGED: Allow overriding resources via .env, default to standard folder
      - ${UI_RESOURCES_PATH:-./public/resources}:/app/public/resources
    env_file:         
      - .env         
    command: npx nodemon server.js
    restart: unless-stopped